DELETE FROM ROLES;
INSERT INTO ROLES (ID, ROLE_NAME) VALUES
  (0, 'UNKNOWN'),
  (1, 'ADMIN'),
  (2, 'EMPLOYEE');

INSERT INTO INSTITUTION_TYPES (ID, TYPE) VALUES
  (0, 'UNKNOWN'),
  (1, 'IDOSEK_OTTHONA'),
  (2, 'CSALADI_BOLCSODE'),
  (3, 'REHABILITACIO'),
  (4, 'HAZI_SEGITSEGNYUJTAS'),
  (5, 'NEVELOSZULOI_HALOZAT');

INSERT INTO CARE_TYPES (ID, CARE_TYPE) VALUES
  (0, 'UNKNOWN'),
  (1, 'IDOSEK_OTTHONA'),
  (2, 'HAZI_SEGITSEG_NYUJTAS'),
  (3, 'CSALADI_BOLCSODE'),
  (4, 'SZENVEDELYBETEGEK_REHABILITACIOJA'),
  (5, 'CSALADI_BOLCSODE'),
  (6, 'CSALADOK_ATMENETI_OTTHONA'),
  (7, 'KULSO_FEROHELY'),
  (8, 'OTTHONT_NYUJTO_ELLATAS'),
  (9, 'KULONLEGES_ELLATAS'),
  (10, 'UTOGONDOZOI_ELLATAS');

INSERT INTO RELATIONSHIPS (ID, RELATIONSHIP) VALUES
  (0, 'UNKNOWN'),
  (1, 'EGYEB'),
  (2, 'HAZASTARS'),
  (3, 'APA'),
  (4, 'ANYA');

INSERT INTO SEX (ID, SEX) VALUES
  (0, 'UNKNOWN'),
  (1, 'FERFI'),
  (2, 'NO');