INSERT INTO ROLES (ID, ROLE_NAME) VALUES
  (0, 'ADMIN'),
  (1, 'EMPLOYEE');

INSERT INTO INSTITUTION_TYPES (ID, TYPE) VALUES
  (0, 'IDOSEK_OTTHONA'),
  (1, 'CSALADI_BOLCSODE'),
  (2, 'REHABILITACIO'),
  (3, 'HAZI_SEGITSEGNYUJTAS'),
  (4, 'NEVELOSZULOI_HALOZAT');

INSERT INTO CARE_TYPES (ID, CARE_TYPE) VALUES
  (0, 'IDOSEK_OTTHONA'),
  (1, 'HAZI_SEGITSEG_NYUJTAS'),
  (2, 'CSALADI_BOLCSODE'),
  (3, 'SZENVEDELYBETEGEK_REHABILITACIOJA'),
  (4, 'CSALADI_BOLCSODE'),
  (5, 'CSALADOK_ATMENETI_OTTHONA'),
  (6, 'KULSO_FEROHELY'),
  (7, 'OTTHONT_NYUJTO_ELLATAS'),
  (8, 'KULONLEGES_ELLATAS'),
  (9, 'UTOGONDOZOI_ELLATAS');

INSERT INTO INSTITUTIONS_TO_USERS (INSTITUTION_ID, USER_ID) VALUES
  (0, 37),
  (1, 37);

INSERT INTO RELATIONSHIPS (ID, RELATIONSHIP) VALUES
  (0, 'OTHER'),
  (1, 'SPOUSE'),
  (2, 'FATHER'),
  (3, 'MOTHER');